services:
  db:
    image: mysql:8.3
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo
      MYSQL_PASSWORD: todopass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass"]
      interval: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: todo-server
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=todo
      - DB_PASSWORD=todopass
      - DB_NAME=todo_db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: todo-client
    depends_on:
      server:
        condition: service_started
    environment:
      - SERVER_URL=http://server:8080

volumes:
  db_data: