name: CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: todo_db
          MYSQL_USER: todo
          MYSQL_PASSWORD: todopass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      MYSQL_USER: todo
      MYSQL_PASSWORD: todopass
      MYSQL_DATABASE: todo_db
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -utodo -ptodopass --silent; then
              echo "MySQL is up!" && break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Run migrations
        run: |
          migrate -path=migration -database "mysql://todo:todopass@tcp(127.0.0.1:3306)/todo_db" up

      - name: Run tests
        run: |
          go test ./internal/repo